# Generated by Django 2.1.5 on 2019-01-09 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderListing',
            fields=[
                ('orderListingId', models.AutoField(primary_key=True, serialize=False)),
                ('productCount', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('shoppingCartId', models.AutoField(primary_key=True, serialize=False)),
                ('sessionKey', models.CharField(max_length=38)),
            ],
        ),
        migrations.AddField(
            model_name='orderlisting',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itemsInCart', to='shoppingCart.ShoppingCart'),
        ),
    ]
