# Generated by Django 2.1.5 on 2019-01-09 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlisting',
            name='shoppingCart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingCartItems', to='shoppingCart.ShoppingCart'),
        ),
    ]
