# Generated by Django 2.1.5 on 2019-01-09 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0002_auto_20190108_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='sessionKey',
            new_name='shoppingCartKey',
        ),
    ]
